"""create_conversations_and_messages

Revision ID: 872ef0943470
Revises: 92473e1649ea
Create Date: 2026-07-11 17:29:30.141274+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872ef0943470'
down_revision: Union[str, None] = '92473e1649ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Auto-generated title from first user message'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Globally unique record identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Original uploaded filename'),
    sa.Column('collection_name', sa.String(length=100), nullable=False, comment='Target ChromaDB collection name'),
    sa.Column('source_id', sa.String(length=36), nullable=False, comment='UUID used as ChromaDB source identifier for deletion'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False, comment='Ingestion lifecycle status'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='Number of pages (or 1 for text files)'),
    sa.Column('chunks_created', sa.Integer(), nullable=False, comment='Number of text chunks generated from this document'),
    sa.Column('chunks_stored', sa.Integer(), nullable=False, comment='Number of chunks successfully stored in ChromaDB'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='Original file size in bytes'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='File extension (pdf, txt, md)'),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True, comment='Time taken to process this document (seconds)'),
    sa.Column('document_title', sa.String(length=500), nullable=True, comment='PDF title extracted from metadata'),
    sa.Column('document_author', sa.String(length=200), nullable=True, comment='PDF author extracted from metadata'),
    sa.Column('description', sa.Text(), nullable=True, comment='User-provided description of this document'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if status=FAILED'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False when document is deleted (soft delete)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Globally unique record identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_collection_name'), 'knowledge_documents', ['collection_name'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_is_active'), 'knowledge_documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_source_id'), 'knowledge_documents', ['source_id'], unique=True)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Parent conversation'),
    sa.Column('role', sa.String(length=16), nullable=False, comment="'user' or 'assistant'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text (markdown for assistant messages)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Globally unique record identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_source_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_is_active'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_collection_name'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_table('conversations')
    # ### end Alembic commands ###
